### ISSUE TITLE
bootstrap-timepicker.js and bootstrap-timepicker.min.js are not the same

### ISSUE THREAD

**Issue by Jermanis** [rendom/bootstrap-3-timepicker#1]
The bootstrap-timepicker.js and bootstrap-timepicker.min.js files have different values for class values for icon-chevron-up and icon-chevron-down. 

bootstrap-timepicker.js works with bootstrap 3.

**Comment by rendom** [comment]
This project is not done, but i should take care of it some day.

**Comment by fighter-jet** [comment]
I had the same problem and it took hours of my time until I found out that these two files are not the same. I explored even some off-topic ways to fix it!

**Comment by rendom** [comment]
I have generated a new minified version now.
