### ISSUE TITLE
Timepicker in 24 hour format

### ISSUE THREAD

**Issue by premtd** [rendom/bootstrap-3-timepicker#6]
I have disabled the  Date Picker by (pickDate: false) as i needed only time picker. 

In time picker it is not coming in 24 hour format even after using  showMeridian: false

Please let me know

Thanks.

**Comment by rendom** [comment]
Are you sure u are using the right plugin? Bc we don't have any date picker integrated in this plugin.

Setting for 24h
`$('#timepicker1').timepicker({showMeridian:false});`
